UPDATE screener SET industrie = 'Banques Régionales' WHERE industrie = 'Banks - Regional';
UPDATE screener SET industrie = 'Services Publics Renouvelables' WHERE industrie = 'Renewable Utilities';
UPDATE screener SET industrie = 'Autres Métaux Précieux' WHERE industrie = 'Other Precious Metals';
UPDATE screener SET industrie = 'Chimie - Spécialité' WHERE industrie = 'Chemicals - Specialty';
UPDATE screener SET industrie = 'Charbon' WHERE industrie = 'Coal';
UPDATE screener SET industrie = 'Services de Crédit Financiers' WHERE industrie = 'Financial - Credit Services';
UPDATE screener SET industrie = 'Plans de Soins Médicaux' WHERE industrie = 'Medical - Healthcare Plans';
UPDATE screener SET industrie = 'Magasins à Prix Réduit' WHERE industrie = 'Discount Stores';
UPDATE screener SET industrie = 'Boissons Non-Alcoolisées' WHERE industrie = 'Beverages - Non-Alcoholic';
UPDATE screener SET industrie = 'Services de Télécommunications' WHERE industrie = 'Telecommunications Services';
UPDATE screener SET industrie = 'Logiciels - Application' WHERE industrie = 'Software - Application';
UPDATE screener SET industrie = 'Semi-Conducteurs' WHERE industrie = 'Semiconductors';
UPDATE screener SET industrie = 'Auto - Pièces' WHERE industrie = 'Auto - Parts';
UPDATE screener SET industrie = 'Restaurants' WHERE industrie = 'Restaurants';
UPDATE screener SET industrie = 'Fabricants de Médicaments - Général' WHERE industrie = 'Drug Manufacturers - General';
UPDATE screener SET industrie = 'Aérospatiale & Défense' WHERE industrie = 'Aerospace & Defense';
UPDATE screener SET industrie = 'Aliments Emballés' WHERE industrie = 'Packaged Foods';
UPDATE screener SET industrie = 'Magasins d'Alimentation' WHERE industrie = 'Grocery Stores';
UPDATE screener SET industrie = 'Vêtements - Chaussures & Accessoires' WHERE industrie = 'Apparel - Footwear & Accessories';
UPDATE screener SET industrie = 'Matériaux Industriels' WHERE industrie = 'Industrial Materials';
UPDATE screener SET industrie = 'Chimie' WHERE industrie = 'Chemicals';
UPDATE screener SET industrie = 'Services en Technologies de l\'Information' WHERE industrie = 'Information Technology Services';
UPDATE screener SET industrie = 'Produits Ménagers & Personnels' WHERE industrie = 'Household & Personal Products';
UPDATE screener SET industrie = 'Assurance - Diversifiée' WHERE industrie = 'Insurance - Diversified';
UPDATE screener SET industrie = 'Produits Agricoles' WHERE industrie = 'Agricultural Farm Products';
UPDATE screener SET industrie = 'Tabac' WHERE industrie = 'Tobacco';
UPDATE screener SET industrie = 'Conglomérats' WHERE industrie = 'Conglomerates';
UPDATE screener SET industrie = 'Boissons - Vignobles & Distilleries' WHERE industrie = 'Beverages - Wineries & Distilleries';
UPDATE screener SET industrie = 'Électronique de Consommation' WHERE industrie = 'Consumer Electronics';
UPDATE screener SET industrie = 'Commerce de Détail Spécialisé' WHERE industrie = 'Specialty Retail';
UPDATE screener SET industrie = 'Équipement de Communication' WHERE industrie = 'Communication Equipment';
UPDATE screener SET industrie = 'Papeterie, Bois & Produits Forestiers' WHERE industrie = 'Paper, Lumber & Forest Products';
UPDATE screener SET industrie = 'Soins Médicaux - Établissements' WHERE industrie = 'Medical - Care Facilities';
UPDATE screener SET industrie = 'Ingénierie & Construction' WHERE industrie = 'Engineering & Construction';
UPDATE screener SET industrie = 'Confiserie Alimentaire' WHERE industrie = 'Food Confectioners';
UPDATE screener SET industrie = 'Gaz Réglementé' WHERE industrie = 'Regulated Gas';
UPDATE screener SET industrie = 'Transport Maritime' WHERE industrie = 'Marine Shipping';
UPDATE screener SET industrie = 'Divertissement' WHERE industrie = 'Entertainment';
UPDATE screener SET industrie = 'Auto - Fabricants' WHERE industrie = 'Auto - Manufacturers';
UPDATE screener SET industrie = 'Exploration & Production de Pétrole & Gaz' WHERE industrie = 'Oil & Gas Exploration & Production';
UPDATE screener SET industrie = 'Raffinage & Marketing de Pétrole & Gaz' WHERE industrie = 'Oil & Gas Refining & Marketing';
UPDATE screener SET industrie = 'Assurance - Vie' WHERE industrie = 'Insurance - Life';
UPDATE screener SET industrie = 'Matériaux de Construction' WHERE industrie = 'Construction Materials';
UPDATE screener SET industrie = 'Immobilier - Services' WHERE industrie = 'Real Estate - Services';
UPDATE screener SET industrie = 'Radiodiffusion' WHERE industrie = 'Broadcasting';
UPDATE screener SET industrie = 'Gestion d\'Actifs' WHERE industrie = 'Asset Management';
UPDATE screener SET industrie = 'Immobilier - Développement' WHERE industrie = 'Real Estate - Development';
UPDATE screener SET industrie = 'Immobilier - Diversifié' WHERE industrie = 'Real Estate - Diversified';
UPDATE screener SET industrie = 'Fabricants de Médicaments - Spécialisés & Génériques' WHERE industrie = 'Drug Manufacturers - Specialty & Generic';
UPDATE screener SET industrie = 'Boissons - Alcoolisées' WHERE industrie = 'Beverages - Alcoholic';
UPDATE screener SET industrie = 'Intégré Pétrole & Gaz' WHERE industrie = 'Oil & Gas Integrated';
UPDATE screener SET industrie = 'Électricité Réglementée' WHERE industrie = 'Regulated Electric';
UPDATE screener SET industrie = 'Distribution Médicale' WHERE industrie = 'Medical - Distribution';
UPDATE screener SET industrie = 'Infrastructures Industrielles' WHERE industrie = 'Industrial - Infrastructure Operations';
UPDATE screener SET industrie = 'Distributeurs de Technologie' WHERE industrie = 'Technology Distributors';
UPDATE screener SET industrie = 'Or' WHERE industrie = 'Gold';
UPDATE screener SET industrie = 'Acier' WHERE industrie = 'Steel';
UPDATE screener SET industrie = 'Compagnies Aériennes, Aéroports & Services Aériens' WHERE industrie = 'Airlines, Airports & Air Services';
UPDATE screener SET industrie = 'Distribution Alimentaire' WHERE industrie = 'Food Distribution';
UPDATE screener SET industrie = 'Véhicules de Loisirs' WHERE industrie = 'Auto - Recreational Vehicles';
UPDATE screener SET industrie = 'Distribution Industrielle' WHERE industrie = 'Industrial - Distribution';
UPDATE screener SET industrie = 'Construction' WHERE industrie = 'Construction';
UPDATE screener SET industrie = 'Concessionnaires Auto' WHERE industrie = 'Auto - Dealerships';
UPDATE screener SET industrie = 'Instruments & Fournitures Médicaux' WHERE industrie = 'Medical - Instruments & Supplies';
UPDATE screener SET industrie = 'Marchés de Capitaux Financiers' WHERE industrie = 'Financial - Capital Markets';
UPDATE screener SET industrie = 'Intrants Agricoles' WHERE industrie = 'Agricultural Inputs';
UPDATE screener SET industrie = 'Logiciels - Infrastructure' WHERE industrie = 'Software - Infrastructure';
UPDATE screener SET industrie = 'Chemins de Fer' WHERE industrie = 'Railroads';
UPDATE screener SET industrie = 'Producteurs d\'Énergie Indépendants' WHERE industrie = 'Independent Power Producers';
UPDATE screener SET industrie = 'Agences de Publicité' WHERE industrie = 'Advertising Agencies';
UPDATE screener SET industrie = 'Biotechnologie' WHERE industrie = 'Biotechnology';
UPDATE screener SET industrie = 'Équipement & Services Pétroliers & Gaziers' WHERE industrie = 'Oil & Gas Equipment & Services';
UPDATE screener SET industrie = 'Magasins de Département' WHERE industrie = 'Department Stores';
UPDATE screener SET industrie = 'Emballage & Contenants' WHERE industrie = 'Packaging & Containers';
UPDATE screener SET industrie = 'Argent' WHERE industrie = 'Silver';
UPDATE screener SET industrie = 'Services de Location & Location' WHERE industrie = 'Rental & Leasing Services';
UPDATE screener SET industrie = 'Transport Routier' WHERE industrie = 'Trucking';
UPDATE screener SET industrie = 'Diagnostics & Recherche Médicaux' WHERE industrie = 'Medical - Diagnostics & Research';
UPDATE screener SET industrie = 'Biens de Luxe' WHERE industrie = 'Luxury Goods';
UPDATE screener SET industrie = 'Assurance - Propriétés & Accidents' WHERE industrie = 'Insurance - Property & Casualty';
UPDATE screener SET industrie = 'Contenu & Informations Internet' WHERE industrie = 'Internet Content & Information';
UPDATE screener SET industrie = 'Machinerie Industrielle' WHERE industrie = 'Industrial - Machinery';
UPDATE screener SET industrie = 'Fabrication - Outils & Accessoires' WHERE industrie = 'Manufacturing - Tools & Accessories';
UPDATE screener SET industrie = 'Amélioration de la Maison' WHERE industrie = 'Home Improvement';
UPDATE screener SET industrie = 'Fabricants de Vêtements' WHERE industrie = 'Apparel - Manufacturers';
UPDATE screener SET industrie = 'Freight & Logistique Intégrés' WHERE industrie = 'Integrated Freight & Logistics';
UPDATE screener SET industrie = 'Vêtements - Vente au Détail' WHERE industrie = 'Apparel - Retail';
UPDATE screener SET industrie = 'Services Spécialisés aux Entreprises' WHERE industrie = 'Specialty Business Services';
UPDATE screener SET industrie = 'Équipement Électrique & Pièces' WHERE industrie = 'Electrical Equipment & Parts';
UPDATE screener SET industrie = 'Eau Réglementée' WHERE industrie = 'Regulated Water';
UPDATE screener SET industrie = 'Jeux Électroniques & Multimédia' WHERE industrie = 'Electronic Gaming & Multimedia';
UPDATE screener SET industrie = 'Mobilier, Équipements & Appareils' WHERE industrie = 'Furnishings, Fixtures & Appliances';
UPDATE screener SET industrie = 'Hébergement de Voyage' WHERE industrie = 'Travel Lodging';
UPDATE screener SET industrie = 'Équipements & Pièces' WHERE industrie = 'Hardware, Equipment & Parts';
UPDATE screener SET industrie = 'Loisirs' WHERE industrie = 'Leisure';
UPDATE screener SET industrie = 'Services de Voyage' WHERE industrie = 'Travel Services';
UPDATE screener SET industrie = 'Matériel Informatique' WHERE industrie = 'Computer Hardware';
UPDATE screener SET industrie = 'Équipements & Fournitures d\'Entreprise' WHERE industrie = 'Business Equipment & Supplies';
UPDATE screener SET industrie = 'Banques' WHERE industrie = 'Banks';
UPDATE screener SET industrie = 'Gestion d\'Actifs - Global' WHERE industrie = 'Asset Management - Global';
UPDATE screener SET industrie = 'Services de Personnel & Emploi' WHERE industrie = 'Staffing & Employment Services';
UPDATE screener SET industrie = 'Fabrication - Fabrication Métallique' WHERE industrie = 'Manufacturing - Metal Fabrication';
UPDATE screener SET industrie = 'Assurance - Réassurance' WHERE industrie = 'Insurance - Reinsurance';
UPDATE screener SET industrie = 'Forage Pétrolier & Gazier' WHERE industrie = 'Oil & Gas Drilling';
UPDATE screener SET industrie = 'Machinerie Agricole' WHERE industrie = 'Agricultural - Machinery';
UPDATE screener SET industrie = 'Aluminium' WHERE industrie = 'Aluminum';
UPDATE screener SET industrie = 'Gestion des Déchets' WHERE industrie = 'Waste Management';
UPDATE screener SET industrie = 'Services de Sécurité & Protection' WHERE industrie = 'Security & Protection Services';
UPDATE screener SET industrie = 'Données Financières & Bourses' WHERE industrie = 'Financial - Data & Stock Exchanges';
UPDATE screener SET industrie = 'Médias & Divertissement' WHERE industrie = 'Media & Entertainment';
UPDATE screener SET industrie = 'Édition' WHERE industrie = 'Publishing';
UPDATE screener SET industrie = 'Construction Résidentielle' WHERE industrie = 'Residential Construction';
UPDATE screener SET industrie = 'Conglomérats Financiers' WHERE industrie = 'Financial - Conglomerates';
UPDATE screener SET industrie = 'Jeux, Stations Balnéaires & Casinos' WHERE industrie = 'Gambling, Resorts & Casinos';
UPDATE screener SET industrie = 'Dispositifs Médicaux' WHERE industrie = 'Medical - Devices';
UPDATE screener SET industrie = 'Hypothèques Financières' WHERE industrie = 'Financial - Mortgages';
UPDATE screener SET industrie = 'Solaire' WHERE industrie = 'Solar';
UPDATE screener SET industrie = 'Transport Général' WHERE industrie = 'General Transportation';
UPDATE screener SET industrie = 'Services Publics Diversifiés' WHERE industrie = 'Diversified Utilities';
UPDATE screener SET industrie = 'Pétrole & Gaz Midstream' WHERE industrie = 'Oil & Gas Midstream';
UPDATE screener SET industrie = 'REIT - Industriel' WHERE industrie = 'REIT - Industrial';
UPDATE screener SET industrie = 'Assurance - Courtiers' WHERE industrie = 'Insurance - Brokers';
UPDATE screener SET industrie = 'REIT - Spécial' WHERE industrie = 'REIT - Specialty';
UPDATE screener SET industrie = 'Industrie - Spécialités' WHERE industrie = 'Industrial - Specialties';
UPDATE screener SET industrie = 'Pharmaceutiques Médicaux' WHERE industrie = 'Medical - Pharmaceuticals';
UPDATE screener SET industrie = 'Cuivre' WHERE industrie = 'Copper';
UPDATE screener SET industrie = 'Logiciels - Services' WHERE industrie = 'Software - Services';
UPDATE screener SET industrie = 'REIT - Établissements de Soins de Santé' WHERE industrie = 'REIT - Healthcare Facilities';
UPDATE screener SET industrie = 'Services de Formation & Éducation' WHERE industrie = 'Education & Training Services';
UPDATE screener SET industrie = 'REIT - Diversifié' WHERE industrie = 'REIT - Diversified';
UPDATE screener SET industrie = 'Gestion d\'Actifs - Revenu' WHERE industrie = 'Asset Management - Income';
UPDATE screener SET industrie = 'Produit de Luxe' WHERE industrie = 'Luxury Goods';