UPDATE industries
SET industry_name = CASE industry_name
    WHEN 'Banks - Regional' THEN 'Banques - Régionales'
    WHEN 'Renewable Utilities' THEN 'Utilités Renouvelables'
    WHEN 'Other Precious Metals' THEN 'Autres Métaux Précieux'
    WHEN 'Specialty Chemicals' THEN 'Chimie - Spécialisée'
    WHEN 'Coal' THEN 'Charbon'
    WHEN 'Financial Services - Credit' THEN 'Services Financiers - Crédit'
    WHEN 'Medical - Health Plans' THEN 'Médical - Plans de Soins'
    WHEN 'Discount Stores' THEN 'Magasins à Prix Réduit'
    WHEN 'Beverages - Non-Alcoholic' THEN 'Boissons - Non-Alcoolisées'
    WHEN 'Telecommunications' THEN 'Télécommunications'
    WHEN 'Software - Application' THEN 'Logiciels - Applications'
    WHEN 'Semiconductors' THEN 'Semi-conducteurs'
    WHEN 'Auto - Parts' THEN 'Auto - Pièces'
    WHEN 'Restaurants' THEN 'Restaurants'
    WHEN 'Pharmaceuticals - General' THEN 'Fabricants de Médicaments - Général'
    WHEN 'Aerospace & Defense' THEN 'Aérospatiale & Défense'
    WHEN 'Packaged Foods' THEN 'Aliments Emballés'
    WHEN 'Grocery Stores' THEN 'Magasins d’Articles de Première Nécessité'
    WHEN 'Apparel - Shoes & Accessories' THEN 'Vêtements - Chaussures & Accessoires'
    WHEN 'Industrial Materials' THEN 'Matériaux Industriels'
    WHEN 'Chemicals' THEN 'Chimie'
    WHEN 'Information Technology - Services' THEN 'Informatique - Services'
    WHEN 'Household & Personal Products' THEN 'Produits Ménagers & Personnels'
    WHEN 'Insurance - Diversified' THEN 'Assurance - Diversifiée'
    WHEN 'Agricultural Products' THEN 'Produits Agricoles'
    WHEN 'Tobacco' THEN 'Tabac'
    WHEN 'Conglomerates' THEN 'Conglomérats'
    WHEN 'Beverages - Wineries & Distilleries' THEN 'Boissons - Vignobles & Distilleries'
    WHEN 'Consumer Electronics' THEN 'Électronique de Consommation'
    WHEN 'Specialty Retail' THEN 'Commerce de Détail Spécialisé'
    WHEN 'Communication Equipment' THEN 'Équipement de Communication'
    WHEN 'Paper, Forest Products & Packaging' THEN 'Papeterie, Bois & Produits Forestiers'
    WHEN 'Medical Care Facilities' THEN 'Soins Médicaux - Établissements'
    WHEN 'Engineering & Construction' THEN 'Ingénierie & Construction'
    WHEN 'Confectionery' THEN 'Confiserie Alimentaire'
    WHEN 'Regulated Gas' THEN 'Gaz Réglementé'
    WHEN 'Marine Transportation' THEN 'Transport Maritime'
    WHEN 'Entertainment' THEN 'Divertissement'
    WHEN 'Auto - Manufacturers' THEN 'Auto - Fabricants'
    WHEN 'Oil & Gas Exploration & Production' THEN 'Exploration & Production de Pétrole & Gaz'
    WHEN 'Oil & Gas Refining & Marketing' THEN 'Raffinage & Marketing de Pétrole & Gaz'
    WHEN 'Insurance - Life' THEN 'Assurance - Vie'
    WHEN 'Building Materials' THEN 'Matériaux de Construction'
    WHEN 'Real Estate - Services' THEN 'Immobilier - Services'
    WHEN 'Broadcasting' THEN 'Radiodiffusion'
    WHEN 'Asset Management' THEN 'Gestion d'Actifs'
    WHEN 'Real Estate - Development' THEN 'Immobilier - Développement'
    WHEN 'Real Estate - Diversified' THEN 'Immobilier - Diversifié'
    WHEN 'Pharmaceuticals - Specialized & Generic' THEN 'Fabricants de Médicaments - Spécialisés & Génériques'
    WHEN 'Beverages - Alcoholic' THEN 'Boissons - Alcoolisées'
    WHEN 'Integrated Oil & Gas' THEN 'Intégré Pétrole & Gaz'
    WHEN 'Regulated Electricity' THEN 'Électricité Réglementée'
    WHEN 'Medical Distribution' THEN 'Distribution Médicale'
    WHEN 'Industrial Infrastructure' THEN 'Infrastructures Industrielles'
    WHEN 'Technology Distributors' THEN 'Distributeurs de Technologie'
    WHEN 'Gold' THEN 'Or'
    WHEN 'Steel' THEN 'Acier'
    WHEN 'Airlines, Airports & Air Services' THEN 'Compagnies Aériennes, Aéroports & Services Aériens'
    WHEN 'Food Distribution' THEN 'Distribution Alimentaire'
    WHEN 'Leisure Vehicles' THEN 'Véhicules de Loisirs'
    WHEN 'Industrial Distribution' THEN 'Distribution Industrielle'
    WHEN 'Construction' THEN 'Construction'
    WHEN 'Auto Dealers' THEN 'Concessionnaires Auto'
    WHEN 'Medical Instruments & Supplies' THEN 'Instruments & Fournitures Médicaux'
    WHEN 'Financial Services - Capital Markets' THEN 'Marchés de Capitaux Financiers'
    WHEN 'Agricultural Inputs' THEN 'Intrants Agricoles'
    WHEN 'Software - Infrastructure' THEN 'Logiciels - Infrastructure'
    WHEN 'Railroads' THEN 'Chemins de Fer'
    WHEN 'Independent Power Producers' THEN 'Producteurs d'Énergie Indépendants'
    WHEN 'Advertising Agencies' THEN 'Agences de Publicité'
    WHEN 'Biotechnology' THEN 'Biotechnologie'
    WHEN 'Oil & Gas Equipment & Services' THEN 'Équipement & Services Pétroliers & Gaziers'
    WHEN 'Department Stores' THEN 'Magasins de Département'
    WHEN 'Packaging & Containers' THEN 'Emballage & Contenants'
    WHEN 'Silver' THEN 'Argent'
    WHEN 'Rental & Leasing Services' THEN 'Services de Location & Location'
    WHEN 'Road Transportation' THEN 'Transport Routier'
    WHEN 'Medical Diagnostics & Research' THEN 'Diagnostics & Recherche Médicaux'
    WHEN 'Luxury Goods' THEN 'Biens de Luxe'
    WHEN 'Insurance - Property & Casualty' THEN 'Assurance - Propriétés & Accidents'
    WHEN 'Internet Content & Information' THEN 'Contenu & Informations Internet'
    WHEN 'Industrial Machinery' THEN 'Machinerie Industrielle'
    WHEN 'Manufacturing - Tools & Accessories' THEN 'Fabrication - Outils & Accessoires'
    WHEN 'Home Improvement' THEN 'Amélioration de la Maison'
    WHEN 'Apparel Manufacturers' THEN 'Fabricants de Vêtements'
    WHEN 'Freight & Logistics' THEN 'Freight & Logistique Intégrés'
    WHEN 'Apparel - Retail' THEN 'Vêtements - Vente au Détail'
    WHEN 'Specialty Business Services' THEN 'Specialty Business Services'
    WHEN 'Electrical Equipment & Parts' THEN 'Electrical Equipment & Parts'
    WHEN 'Regulated Water' THEN 'Regulated Water'
    WHEN 'Electronic Gaming & Multimedia' THEN 'Electronic Gaming & Multimedia'
    WHEN 'Furnishings, Fixtures & Appliances' THEN 'Furnishings, Fixtures & Appliances'
    WHEN 'Travel Lodging' THEN 'Travel Lodging'
    WHEN 'Hardware, Equipment & Parts' THEN 'Hardware, Equipment & Parts'
    WHEN 'Leisure' THEN 'Leisure'
    WHEN 'Travel Services' THEN 'Travel Services'
    WHEN 'Computer Hardware' THEN 'Computer Hardware'
    WHEN 'Business Equipment & Supplies' THEN 'Business Equipment & Supplies'
    WHEN 'Banks - Diversified' THEN 'Banks - Diversified'
    WHEN 'Staffing & Employment Services' THEN 'Staffing & Employment Services'
    WHEN 'Manufacturing - Metal Fabrication' THEN 'Manufacturing - Metal Fabrication'
    WHEN 'Insurance - Reinsurance' THEN 'Insurance - Reinsurance'
    WHEN 'Oil & Gas Drilling' THEN 'Oil & Gas Drilling'
    WHEN 'Agricultural - Machinery' THEN 'Agricultural - Machinery'
    WHEN 'Aluminum' THEN 'Aluminum'
    WHEN 'Waste Management' THEN 'Waste Management'
    WHEN 'Security & Protection Services' THEN 'Security & Protection Services'
    WHEN 'Financial - Data & Stock Exchanges' THEN 'Financial - Data & Stock Exchanges'
    WHEN 'Media & Entertainment' THEN 'Media & Entertainment'
    WHEN 'Publishing' THEN 'Publishing'
    WHEN 'Residential Construction' THEN 'Residential Construction'
    WHEN 'Financial - Conglomerates' THEN 'Financial - Conglomerates'
    WHEN 'Gambling, Resorts & Casinos' THEN 'Gambling, Resorts & Casinos'
    WHEN 'Medical - Devices' THEN 'Medical - Devices'
    WHEN 'Financial - Mortgages' THEN 'Financial - Mortgages'
    WHEN 'Solar' THEN 'Solar'
    WHEN 'General Transportation' THEN 'General Transportation'
    WHEN 'Diversified Utilities' THEN 'Diversified Utilities'
    WHEN 'Oil & Gas Midstream' THEN 'Oil & Gas Midstream'
    WHEN 'REIT - Industrial' THEN 'REIT - Industriel'
    WHEN 'Insurance - Brokers' THEN 'Insurance - Courtiers'
    WHEN 'REIT - Specialized' THEN 'REIT - Spécialisé'
    WHEN 'Industrial - Specialties' THEN 'Industriel - Spécialités'
    WHEN 'Medical - Pharmaceuticals' THEN 'Médical - Pharmaceutiques'
    WHEN 'Copper' THEN 'Cuivre'
    WHEN 'Biotech - Genomics' THEN 'Biotechnologie - Génomique'
    ELSE industry_name
END;
