UPDATE screener SET industrie = 'Banques - Régionales' WHERE industrie = 'Banks - Regional';
UPDATE screener SET industrie = 'Utilités Renouvelables' WHERE industrie = 'Renewable Utilities';
UPDATE screener SET industrie = 'Autres Métaux Précieux' WHERE industrie = 'Other Precious Metals';
UPDATE screener SET industrie = 'Chimie - Spécialisée' WHERE industrie = 'Chemicals - Specialty';
UPDATE screener SET industrie = 'Charbon' WHERE industrie = 'Coal';
UPDATE screener SET industrie = 'Services Financiers - Crédit' WHERE industrie = 'Financial - Credit Services';
UPDATE screener SET industrie = 'Médical - Plans de Soins' WHERE industrie = 'Medical - Healthcare Plans';
UPDATE screener SET industrie = 'Magasins à Prix Réduit' WHERE industrie = 'Discount Stores';
UPDATE screener SET industrie = 'Boissons - Non-Alcoolisées' WHERE industrie = 'Beverages - Non-Alcoholic';
UPDATE screener SET industrie = 'Télécommunications' WHERE industrie = 'Telecommunications Services';
UPDATE screener SET industrie = 'Logiciels - Applications' WHERE industrie = 'Software - Application';
UPDATE screener SET industrie = 'Semi-conducteurs' WHERE industrie = 'Semiconductors';
UPDATE screener SET industrie = 'Auto - Pièces' WHERE industrie = 'Auto - Parts';
UPDATE screener SET industrie = 'Restaurants' WHERE industrie = 'Restaurants';
UPDATE screener SET industrie = 'Fabricants de Médicaments - Général' WHERE industrie = 'Drug Manufacturers - General';
UPDATE screener SET industrie = 'Aérospatiale & Défense' WHERE industrie = 'Aerospace & Defense';
UPDATE screener SET industrie = 'Aliments Emballés' WHERE industrie = 'Packaged Foods';
UPDATE screener SET industrie = 'Magasins d’Articles de Première Nécessité' WHERE industrie = 'Grocery Stores';
UPDATE screener SET industrie = 'Vêtements - Chaussures & Accessoires' WHERE industrie = 'Apparel - Footwear & Accessories';
UPDATE screener SET industrie = 'Matériaux Industriels' WHERE industrie = 'Industrial Materials';
UPDATE screener SET industrie = 'Chimie' WHERE industrie = 'Chemicals';
UPDATE screener SET industrie = 'Services en Technologies de l'Information' WHERE industrie = 'Information Technology Services';
UPDATE screener SET industrie = 'Produits de Consommation & Personnels' WHERE industrie = 'Household & Personal Products';
UPDATE screener SET industrie = 'Assurance - Diversifiée' WHERE industrie = 'Insurance - Diversified';
UPDATE screener SET industrie = 'Produits Agricoles' WHERE industrie = 'Agricultural Farm Products';
UPDATE screener SET industrie = 'Tabac' WHERE industrie = 'Tobacco';
UPDATE screener SET industrie = 'Conglomérats' WHERE industrie = 'Conglomerates';
UPDATE screener SET industrie = 'Boissons - Vignobles & Distilleries' WHERE industrie = 'Beverages - Wineries & Distilleries';
UPDATE screener SET industrie = 'Électronique de Consommation' WHERE industrie = 'Consumer Electronics';
UPDATE screener SET industrie = 'Commerce de Spécialités' WHERE industrie = 'Specialty Retail';
UPDATE screener SET industrie = 'Équipement de Communication' WHERE industrie = 'Communication Equipment';
UPDATE screener SET industrie = 'Papeterie, Bois & Produits Forestiers' WHERE industrie = 'Paper, Lumber & Forest Products';
UPDATE screener SET industrie = 'Médical - Établissements de Soins' WHERE industrie = 'Medical - Care Facilities';
UPDATE screener SET industrie = 'Ingénierie & Construction' WHERE industrie = 'Engineering & Construction';
UPDATE screener SET industrie = 'Confiserie Alimentaire' WHERE industrie = 'Food Confectioners';
UPDATE screener SET industrie = 'Gaz Réglementé' WHERE industrie = 'Regulated Gas';
UPDATE screener SET industrie = 'Transport Maritime' WHERE industrie = 'Marine Shipping';
UPDATE screener SET industrie = 'Divertissement' WHERE industrie = 'Entertainment';
UPDATE screener SET industrie = 'Auto - Fabricants' WHERE industrie = 'Auto - Manufacturers';
UPDATE screener SET industrie = 'Exploration & Production de Pétrole & Gaz' WHERE industrie = 'Oil & Gas Exploration & Production';
UPDATE screener SET industrie = 'Raffinage & Marketing de Pétrole & Gaz' WHERE industrie = 'Oil & Gas Refining & Marketing';
UPDATE screener SET industrie = 'Assurance - Vie' WHERE industrie = 'Insurance - Life';
UPDATE screener SET industrie = 'Matériaux de Construction' WHERE industrie = 'Construction Materials';
UPDATE screener SET industrie = 'Immobilier - Services' WHERE industrie = 'Real Estate - Services';
UPDATE screener SET industrie = 'Diffusion' WHERE industrie = 'Broadcasting';
UPDATE screener SET industrie = 'Gestion d’Actifs' WHERE industrie = 'Asset Management';
UPDATE screener SET industrie = 'Immobilier - Développement' WHERE industrie = 'Real Estate - Development';
UPDATE screener SET industrie = 'Immobilier - Diversifié' WHERE industrie = 'Real Estate - Diversified';
UPDATE screener SET industrie = 'Fabricants de Médicaments - Spécialisés & Génériques' WHERE industrie = 'Drug Manufacturers - Specialty & Generic';
UPDATE screener SET industrie = 'Boissons - Alcoolisées' WHERE industrie = 'Beverages - Alcoholic';
UPDATE screener SET industrie = 'Pétrole & Gaz Intégré' WHERE industrie = 'Oil & Gas Integrated';
UPDATE screener SET industrie = 'Électricité Réglementée' WHERE industrie = 'Regulated Electric';
UPDATE screener SET industrie = 'Médical - Distribution' WHERE industrie = 'Medical - Distribution';
UPDATE screener SET industrie = 'Infrastructure Industrielle' WHERE industrie = 'Industrial - Infrastructure Operations';
UPDATE screener SET industrie = 'Distributeurs de Technologie' WHERE industrie = 'Technology Distributors';
UPDATE screener SET industrie = 'Or' WHERE industrie = 'Gold';
UPDATE screener SET industrie = 'Acier' WHERE industrie = 'Steel';
UPDATE screener SET industrie = 'Compagnies Aériennes, Aéroports & Services Aériens' WHERE industrie = 'Airlines, Airports & Air Services';
UPDATE screener SET industrie = 'Distribution Alimentaire' WHERE industrie = 'Food Distribution';
UPDATE screener SET industrie = 'Auto - Véhicules Récréatifs' WHERE industrie = 'Auto - Recreational Vehicles';
UPDATE screener SET industrie = 'Distribution Industrielle' WHERE industrie = 'Industrial - Distribution';
UPDATE screener SET industrie = 'Construction' WHERE industrie = 'Construction';
UPDATE screener SET industrie = 'Auto - Concessionnaires' WHERE industrie = 'Auto - Dealerships';
UPDATE screener SET industrie = 'Médical - Instruments & Fournitures' WHERE industrie = 'Medical - Instruments & Supplies';
UPDATE screener SET industrie = 'Services Financiers - Marchés de Capitaux' WHERE industrie = 'Financial - Capital Markets';
UPDATE screener SET industrie = 'Intrants Agricoles' WHERE industrie = 'Agricultural Inputs';
UPDATE screener SET industrie = 'Logiciels - Infrastructure' WHERE industrie = 'Software - Infrastructure';
UPDATE screener SET industrie = 'Chemins de Fer' WHERE industrie = 'Railroads';
UPDATE screener SET industrie = 'Producteurs d’Énergie Indépendants' WHERE industrie = 'Independent Power Producers';
UPDATE screener SET industrie = 'Agences de Publicité' WHERE industrie = 'Advertising Agencies';
UPDATE screener SET industrie = 'Biotechnologie' WHERE industrie = 'Biotechnology';
UPDATE screener SET industrie = 'Équipements & Services Pétroliers & Gaziers' WHERE industrie = 'Oil & Gas Equipment & Services';
UPDATE screener SET industrie = 'Magasins de Département' WHERE industrie = 'Department Stores';
UPDATE screener SET industrie = 'Emballage & Conteneurs' WHERE industrie = 'Packaging & Containers';
UPDATE screener SET industrie = 'Argent' WHERE industrie = 'Silver';
UPDATE screener SET industrie = 'Services de Location & Bail' WHERE industrie = 'Rental & Leasing Services';
UPDATE screener SET industrie = 'Transport Routier' WHERE industrie = 'Trucking';
UPDATE screener SET industrie = 'Médical - Diagnostics & Recherche' WHERE industrie = 'Medical - Diagnostics & Research';
UPDATE screener SET industrie = 'Biens de Luxe' WHERE industrie = 'Luxury Goods';
UPDATE screener SET industrie = 'Assurance - Propriétés & Accidents' WHERE industrie = 'Insurance - Property & Casualty';
UPDATE screener SET industrie = 'Contenu & Information sur Internet' WHERE industrie = 'Internet Content & Information';
UPDATE screener SET industrie = 'Machinerie Industrielle' WHERE industrie = 'Industrial - Machinery';
UPDATE screener SET industrie = 'Fabrication - Outils & Accessoires' WHERE industrie = 'Manufacturing - Tools & Accessories';
UPDATE screener SET industrie = 'Amélioration de l’Habitat' WHERE industrie = 'Home Improvement';
UPDATE screener SET industrie = 'Vêtements - Fabricants' WHERE industrie = 'Apparel - Manufacturers';
UPDATE screener SET industrie = 'Logistique Intégrée' WHERE industrie = 'Integrated Freight & Logistics';
UPDATE screener SET industrie = 'Vêtements - Vente au Détail' WHERE industrie = 'Apparel - Retail';
UPDATE screener SET industrie = 'Services d’Affaires Spécialisés' WHERE industrie = 'Specialty Business Services';
UPDATE screener SET industrie = 'Équipement & Pièces Électriques' WHERE industrie = 'Electrical Equipment & Parts';
UPDATE screener SET industrie = 'Eau Réglementée' WHERE industrie = 'Regulated Water';
UPDATE screener SET industrie = 'Services Financiers - Diversifiés' WHERE industrie = 'Financial - Diversified Services';
UPDATE screener SET industrie = 'Équipement Médical & Services' WHERE industrie = 'Medical Equipment & Services';
UPDATE screener SET industrie = 'Hôpitaux & Services de Soins de Santé' WHERE industrie = 'Hospitals & Healthcare Services';
UPDATE screener SET industrie = 'Ressources Naturelles' WHERE industrie = 'Natural Resources';
UPDATE screener SET industrie = 'Biens Immobiliers' WHERE industrie = 'Real Estate Assets';
UPDATE screener SET industrie = 'Vente au Détail en Ligne' WHERE industrie = 'Online Retail';
UPDATE screener SET industrie = 'Énergie - Renouvelable & Alternative' WHERE industrie = 'Energy - Renewable & Alternative';
UPDATE screener SET industrie = 'Magasins d’Articles Électroniques' WHERE industrie = 'Electronics Stores';
UPDATE screener SET industrie = 'Fournitures & Équipements Médicaux' WHERE industrie = 'Medical Supplies & Equipment';
UPDATE screener SET industrie = 'Services de Paiement & Transfert d’Argent' WHERE industrie = 'Payment & Money Transfer Services';
UPDATE screener SET industrie = 'Outils & Équipements Industriels' WHERE industrie = 'Industrial Tools & Equipment';
UPDATE screener SET industrie = 'Produits Pharmaceutiques & Biologiques' WHERE industrie = 'Pharmaceuticals & Biologics';
UPDATE screener SET industrie = 'Fournitures & Équipements de Bureau' WHERE industrie = 'Office Supplies & Equipment';
UPDATE screener SET industrie = 'Vêtements - Créateurs' WHERE industrie = 'Apparel - Designers';
UPDATE screener SET industrie = 'Services aux Entreprises' WHERE industrie = 'Business Services';
UPDATE screener SET industrie = 'Technologie Médicale' WHERE industrie = 'Medical Technology';
UPDATE screener SET industrie = 'Fabricants de Matériel Informatique' WHERE industrie = 'Computer Hardware Manufacturers';
UPDATE screener SET industrie = 'Luxe - Biens de Consommation' WHERE industrie = 'Luxury - Consumer Goods';
UPDATE screener SET industrie = 'Énergie - Fossile' WHERE industrie = 'Energy - Fossil';
UPDATE screener SET industrie = 'Médical - Soins à Domicile' WHERE industrie = 'Medical - Home Care';
UPDATE screener SET industrie = 'Services aux Consommateurs' WHERE industrie = 'Consumer Services';
UPDATE screener SET industrie = 'Construction - Génie Civil' WHERE industrie = 'Construction - Civil Engineering';
UPDATE screener SET industrie = 'Transport - Maritime' WHERE industrie = 'Maritime Transport';
UPDATE screener SET industrie = 'Fonds d’Investissement' WHERE industrie = 'Investment Funds';
UPDATE screener SET industrie = 'Matériel & Équipements Électriques' WHERE industrie = 'Electrical Equipment & Hardware';
UPDATE screener SET industrie = 'Assurance - Santé' WHERE industrie = 'Health Insurance';
UPDATE screener SET industrie = 'Technologie - Semiconducteurs' WHERE industrie = 'Technology - Semiconductors';
UPDATE screener SET industrie = 'Énergie - Production & Distribution' WHERE industrie = 'Energy - Production & Distribution';
UPDATE screener SET industrie = 'Ressources Naturelles - Minéraux' WHERE industrie = 'Natural Resources - Minerals';
UPDATE screener SET industrie = 'Technologie - Logiciels' WHERE industrie = 'Technology - Software';
UPDATE screener SET industrie = 'Santé - Biotechnologie' WHERE industrie = 'Healthcare - Biotechnology';
UPDATE screener SET industrie = 'Divertissement - Médias' WHERE industrie = 'Entertainment - Media';
UPDATE screener SET industrie = 'Services Financiers - Banques' WHERE industrie = 'Financial - Banking Services';
UPDATE screener SET industrie = 'Immobilier - Investissement' WHERE industrie = 'Real Estate - Investment';
UPDATE screener SET industrie = 'Énergie - Énergies Renouvelables' WHERE industrie = 'Energy - Renewable Energies';
UPDATE screener SET industrie = 'Services de Nettoyage' WHERE industrie = 'Cleaning Services';
UPDATE screener SET industrie = 'Équipement & Fournitures de Bureau' WHERE industrie = 'Office Equipment & Supplies';
UPDATE screener SET industrie = 'Publicité & Marketing' WHERE industrie = 'Advertising & Marketing';
UPDATE screener SET industrie = 'Services Professionnels' WHERE industrie = 'Professional Services';
UPDATE screener SET industrie = 'Fabrication - Biens Durables' WHERE industrie = 'Durable Goods Manufacturing';
UPDATE screener SET industrie = 'Agriculture - Cultures' WHERE industrie = 'Agriculture - Crops';
UPDATE screener SET industrie = 'Fournitures de Bureau' WHERE industrie = 'Office Supplies';
UPDATE screener SET industrie = 'Technologie - Matériel' WHERE industrie = 'Technology - Hardware';
UPDATE screener SET industrie = 'Métaux de Base' WHERE industrie = 'Base Metals';
UPDATE screener SET industrie = 'Biens de Consommation - Durable' WHERE industrie = 'Consumer Goods - Durable';
UPDATE screener SET industrie = 'Gestion des Investissements' WHERE industrie = 'Investment Management';
UPDATE screener SET industrie = 'Services de Transports' WHERE industrie = 'Transport Services';
UPDATE screener SET industrie = 'Logistique & Chaîne d’Approvisionnement' WHERE industrie = 'Logistics & Supply Chain';
UPDATE screener SET industrie = 'Énergie - Electricité & Gaz' WHERE industrie = 'Energy - Electricity & Gas';
UPDATE screener SET industrie = 'Énergie - Énergie Électrique' WHERE industrie = 'Energy - Electrical Energy';
UPDATE screener SET industrie = 'Industrie Aérospatiale' WHERE industrie = 'Aerospace Industry';
UPDATE screener SET industrie = 'Fournitures & Équipements de Construction' WHERE industrie = 'Construction Supplies & Equipment';
UPDATE screener SET industrie = 'Ressources - Métaux' WHERE industrie = 'Resources - Metals';
UPDATE screener SET industrie = 'Services de Réparation & Entretien' WHERE industrie = 'Repair & Maintenance Services';
UPDATE screener SET industrie = 'Technologie - Logiciels de Sécurité' WHERE industrie = 'Software - Security';
UPDATE screener SET industrie = 'Énergie - Gaz Naturel' WHERE industrie = 'Energy - Natural Gas';
UPDATE screener SET industrie = 'Matériel de Bureau & Fournitures' WHERE industrie = 'Office Equipment & Supplies';
UPDATE screener SET industrie = 'Services d’Assurance' WHERE industrie = 'Insurance Services';
UPDATE screener SET industrie = 'Équipements de Construction' WHERE industrie = 'Construction Equipment';
UPDATE screener SET industrie = 'Biens de Consommation - Non-Durables' WHERE industrie = 'Consumer Goods - Non-Durable';
UPDATE screener SET industrie = 'Énergie - Énergies Fossiles' WHERE industrie = 'Energy - Fossil Fuels';
UPDATE screener SET industrie = 'Matériel de Soins Médicaux' WHERE industrie = 'Medical Equipment';
UPDATE screener SET industrie = 'Services Médicaux' WHERE industrie = 'Medical Services';
UPDATE screener SET industrie = 'Agroalimentaire' WHERE industrie = 'Agri-food';
UPDATE screener SET industrie = 'Transport - Aérien' WHERE industrie = 'Air Transport';
UPDATE screener SET industrie = 'Commerce de Gros' WHERE industrie = 'Wholesale Trade';
UPDATE screener SET industrie = 'Technologie - Équipements de Communication' WHERE industrie = 'Technology - Communication Equipment';
UPDATE screener SET industrie = 'Énergie - Production d’Électricité' WHERE industrie = 'Energy - Electricity Production';
UPDATE screener SET industrie = 'Médical - Soins et Services' WHERE industrie = 'Medical - Care and Services';
UPDATE screener SET industrie = 'Agriculture - Élevage' WHERE industrie = 'Agriculture - Livestock';
UPDATE screener SET industrie = 'Énergie - Production & Distribution d’Électricité' WHERE industrie = 'Energy - Electricity Production & Distribution';
